services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eidos-app
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    ports:
      - "8100:80"
    depends_on:
      - db
    working_dir: /var/www/html

  vite:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eidos-vite
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    ports:
      - "5173:5173"
    working_dir: /var/www/html
    command: ./node_modules/.bin/vite

  db:
    image: mysql:8.0
    container_name: eidos-db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
