services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eidos-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: eidos-db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE_TEST: '${DB_DATABASE_TEST}'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
