services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eidos-app
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    ports:
      - "8000:80"
    depends_on:
      - db
    working_dir: /var/www/html
    networks:
      - eidos-network

  vite:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eidos-vite
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    ports:
      - "5173:5173"
    working_dir: /var/www/html
    command: npm run dev
    networks:
      - eidos-network

  db:
    image: mysql:8.0
    container_name: eidos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - eidos-network

volumes:
  db-data:

networks:
  eidos-network:
    driver: bridge
