services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eidos-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  # --- NOVO SERVIÇO PARA O VITE ---
  vite:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eidos-vite
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173" # Expõe a porta do Vite para o seu computador
    command: npm run dev # Sobrescreve o comando padrão do Dockerfile

  db:
    image: mysql:8.0
    container_name: eidos-db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
